
- name: Create a k8s namespace
  kubernetes.core.k8s:
    name: production
    api_version: v1
    kind: Namespace
    state: present
    kubeconfig: /Users/chchandr/.kube/conf_linode

- name: Deploy Helm Chart in Production
  kubernetes.core.helm:
    kubeconfig: /Users/chchandr/.kube/conf_linode
    name: my-production-release
    chart_ref: "{{ playbook_dir }}/helm_charts/webapp"
    release_namespace: production
    release_state: present
    values_files:
      - "{{ playbook_dir }}/roles/production/files/values.yaml"
