# webapp-chart/templates/flaskapp-secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  namespace: {{ .Values.namespace }}
  name: mysql-secret
type: Opaque
data:
  MYSQL_DATABASE_PASSWORD: cXdlcnR5MTIzNDU2Iw==