# webapp-chart/templates/frontend-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Values.namespace }}
  name: front-end-nginx-deployment
  labels:
    app: nginx
spec:
  replicas: {{ .Values.frontend.replicas }}
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: {{ .Values.frontend.image }}
        ports:
        - containerPort: {{ .Values.frontend.containerPort }}