# Default values for your Helm chart
namespace: production

flaskapp:
  replicas: 1
  image: chiju/flask-api
  tag: v3
  resources:
    limits:
      cpu: "1"
      memory: "512Mi"
    requests:
      cpu: "0.5"
      memory: "256Mi"
  service:
    port: 80
    type: ClusterIP
  hpa:
    minReplicas: 1
    maxReplicas: 5
    targetCPUUtilizationPercentage: 50

frontend:
  replicas: 1
  image: nginx
  tag: latest
  containerPort: 80
  hpa:
    minReplicas: 1
    maxReplicas: 5
    targetCPUUtilizationPercentage: 50

mysql:
  user: xxx
  database: xxx
  host: 'xxxx'
  port: "xxx"
  password: xxxxx

loadbalancer:
  port: 80
  targetPort: 80
