# webapp-chart/templates/flaskapp-hpa.yaml
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  namespace: {{ .Values.namespace }}
  name: flaskapp-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: flaskapp-deployment
  minReplicas: {{ .Values.flaskapp.hpa.minReplicas }}
  maxReplicas: {{ .Values.flaskapp.hpa.maxReplicas }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ .Values.flaskapp.hpa.targetCPUUtilizationPercentage }}